const db = require('../db')
const { Products, Brands} = require('../models')



db.on('error', console.error.bind(console, 'MongoDB connection error:'))



const main = async () => {

  const sony = await Parent.find({ name: 'name' })
  const bose = await Parent.find({ name: 'name' })
  const yamaha = await Parent.find({ name: 'name' })
  const denon = await Parent.find({ name: 'name' })
  const pioneer = await Parent.find({ name: 'Pioneer' })
  const devialet = await Parent.find({ name: 'Devialet' })
  const lgElectronics = await Parent.find({ name: 'LG Electronics' })
  const vizio = await Parent.find({ name: 'VIZIO' })
  const logitech = await Parent.find({ name: 'Logitech' })
  const marantz = await Parent.find({ name: 'Marantz' })
  const sharpCorp = await Parent.find({ name: 'Sharp Corporation' }) 

  const Products = [
    {
      name: 'Sony - STRDH190- 2-Ch. Stereo Receiver',
      description: 'The STR-DH190 stereo receiver delivers quality sound from vinyl and digital music BLUETOOTH® connectivity. Pair with turntables including PS-HX500 and PS-LX310BT to amplify your records. ',
      price: 199.99,
      imageUrl: "https://m.media-amazon.com/images/I/61vJ6wJG5fL.jpg",
      color:'Black',
      isWireless: true,
      isBluetoothEnabled: true,
      isWaterProof: false,
      isPortable: false,
      brand_id: sony[0]._id,
    },
    {
      name: 'Sony - STRDH590 - 725W 5.2-Ch. Home Theater Receiver',
      description: ' The 5.2ch AV receiver brings movies to life with 4K HDR pass-through, Dolby Vision and flexible surround sound. ',
      price: 349.99,
      imageUrl: "https://m.media-amazon.com/images/I/51RAYidyp-L.jpg",
      color:'Black',
      isWireless: true,
      isBluetoothEnabled: true,
      isWaterProof: false,
      isPortable: false,
      brand_id: sony[0]._id,
    },
    {
      name: 'Sony - Portable Theater System with 360 Spatial Sound',
      description: 'The HT-AX7 uses 360 Spatial Sound Mapping technology to envelop you in spatial sound by creating multiple phantom speakers at the front and rear.',
      price: 499.99,
      imageUrl: "https://m.media-amazon.com/images/I/91HDZuw8QDL.jpg",
      color:'Silver',
      isWireless: true,
      isBluetoothEnabled: true,
      isWaterProof: false,
      isPortable: true,
      brand_id: sony[0]._id,
    },

    // Bose
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      isWaterProof: Boolean,
      brand_id: bose[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: bose[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: bose[0]._id,
    },
    // Yamaha
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: yamaha[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: yamaha[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: yamaha[0]._id,
    },
    // Denon
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: denon[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: denon[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: denon[0]._id,
    },
    // Pioneer
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: pioneer[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: pioneer[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: pioneer[0]._id,
    },
    // Devialet
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: devialet[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: devialet[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: devialet[0]._id,
    },
    // LG Electronics
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: lgElectronics[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: lgElectronics[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: lgElectronics[0]._id,
    },
    // VIZIO
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: vizio[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: vizio[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: vizio[0]._id,
    },
    // Logitech
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: logitech[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: logitech[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: logitech[0]._id,
    },
    // Marantz
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: marantz[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: marantz[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: marantz[0]._id,
    },
    // Sharp Corporation
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: sharpCorp[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: sharpCorp[0]._id,
    },
    {
      name: 'string',
      description: 'string',
      price: 1337,
      imageUrl: "link to product here, for my own use",
      color:'string',
      isWireless: Boolean,
      isBluetoothEnabled: Boolean,
      isWaterProof: Boolean,
      isPortable: Boolean,
      brand_id: sharpCorp[0]._id,
    },
  ]
  
  

  await Product.insertMany(product) 

  console.log('============================')
  console.log('PRODUCTS have been seeded!')
  console.log('============================')

}

const run = async () => {

  await main()
  
  db.close()
}

run()